services:
  backend:
    build: .
    container_name: bookstore-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}  
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run dev"
